// bench/react-medium/src/components/Search.tsx
import { useId } from 'react';

interface Props {
  value: string;
  hits: number;
  onChange: (value: string) => void;
}

export default function Search({ value, hits, onChange }: Props) {
  const id = useId();
  return (
    <label className="search">
      <span className="facet-label" id={id}>Search</span>
      <input
        type="search"
        placeholder="Filter by name or brand"
        value={value}
        aria-labelledby={id}
        onChange={(e) => onChange(e.target.value)}
      />
      <span className="search-hits">{hits} matching</span>
    </label>
  );
}

// bench/svelte-medium/src/components/Search.svelte
<script lang="ts">
  let { value, hits, onChange }: { value: string; hits: number; onChange: (value: string) => void } = $props();
  // mirrors Markout's $id-derived unique id for aria-labelledby
  const id = 'search-' + Math.random().toString(36).slice(2);
</script>

<label class="search">
  <span class="facet-label" {id}>Search</span>
  <input
    type="search"
    placeholder="Filter by name or brand"
    {value}
    aria-labelledby={id}
    oninput={(e) => onChange((e.currentTarget as HTMLInputElement).value)}
  />
  <span class="search-hits">{hits} matching</span>
</label>
