// packages/cli/bench/svelte-medium/src/components/Pager.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  let { current, count, prev, next }: { current: number; count: number; prev: Snippet; next: Snippet } = $props();
</script>

<nav class="pager">
  {@render prev()}
  <span class="pager-label">Page {current} of {count}</span>
  {@render next()}
</nav>

// packages/cli/bench/react-medium/src/components/Pager.tsx
import type { ReactNode } from 'react';

interface Props {
  current: number;
  count: number;
  prev: ReactNode;
  next: ReactNode;
}

export default function Pager({ current, count, prev, next }: Props) {
  return (
    <nav className="pager">
      {prev}
      <span className="pager-label">Page {current} of {count}</span>
      {next}
    </nav>
  );
}
