// packages/cli/bench/svelte-catalog/src/components/Facet.svelte
<script lang="ts">
  let { label, options, active, onPick }: {
    label: string;
    options: string[];
    active: string;
    onPick: (value: string) => void;
  } = $props();
</script>

<div class="facet">
  <p class="facet-label">{label}</p>
  <div class="facet-options">
    {#each options as opt (opt)}
      <button class={'chip' + (opt === active ? ' chip-on' : '')} onclick={() => onPick(opt)}>{opt}</button>
    {/each}
  </div>
</div>

// bench/react-medium/src/components/Facet.tsx
interface Props {
  label: string;
  options: string[];
  active: string;
  onPick: (value: string) => void;
}

export default function Facet({ label, options, active, onPick }: Props) {
  return (
    <div className="facet">
      <p className="facet-label">{label}</p>
      <div className="facet-options">
        {options.map((opt) => (
          <button
            key={opt}
            className={'chip' + (opt === active ? ' chip-on' : '')}
            onClick={() => onPick(opt)}
          >
            {opt}
          </button>
        ))}
      </div>
    </div>
  );
}
