// packages/cli/bench/vue-catalog/src/components/Facet.vue
<script setup vapor lang="ts">
defineProps<{ label: string; options: string[]; active: string }>();
defineEmits<{ pick: [value: string] }>();
</script>

<template>
  <div class="facet">
    <p class="facet-label">{{ label }}</p>
    <div class="facet-options">
      <button
        v-for="opt in options"
        :key="opt"
        :class="'chip' + (opt === active ? ' chip-on' : '')"
        @click="$emit('pick', opt)"
      >{{ opt }}</button>
    </div>
  </div>
</template>

// bench/react-medium/src/components/Facet.tsx
interface Props {
  label: string;
  options: string[];
  active: string;
  onPick: (value: string) => void;
}

export default function Facet({ label, options, active, onPick }: Props) {
  return (
    <div className="facet">
      <p className="facet-label">{label}</p>
      <div className="facet-options">
        {options.map((opt) => (
          <button
            key={opt}
            className={'chip' + (opt === active ? ' chip-on' : '')}
            onClick={() => onPick(opt)}
          >
            {opt}
          </button>
        ))}
      </div>
    </div>
  );
}
