// packages/cli/bench/vue-catalog/src/components/Header.vue
<script setup vapor lang="ts">
withDefaults(
  defineProps<{ brand?: string; tagline: string; count: number; total: number }>(),
  { brand: 'Markout' },
);
defineEmits<{ reset: [] }>();
</script>

<template>
  <header class="app-header">
    <div class="brand-block">
      <span class="brand">{{ brand }}</span>
      <span class="tagline">{{ tagline }}</span>
    </div>
    <div class="header-actions">
      <button class="ghost" @click="$emit('reset')">Reset view</button>
      <span class="header-cart"><strong>{{ count }}</strong> in cart &middot; <strong>${{ total }}</strong></span>
    </div>
  </header>
</template>

// bench/react-medium/src/components/Header.tsx
interface Props {
  brand?: string;
  tagline: string;
  count: number;
  total: number;
  onReset: () => void;
}

export default function Header({ brand = 'Markout', tagline, count, total, onReset }: Props) {
  return (
    <header className="app-header">
      <div className="brand-block">
        <span className="brand">{brand}</span>
        <span className="tagline">{tagline}</span>
      </div>
      <div className="header-actions">
        <button className="ghost" onClick={onReset}>Reset view</button>
        <span className="header-cart">
          <strong>{count}</strong> in cart &middot; <strong>${total}</strong>
        </span>
      </div>
    </header>
  );
}
