// bench/svelte-medium/src/components/Rating.svelte
<script lang="ts">
  let { score, count }: { score: number; count: number } = $props();
</script>

<span class="rating">
  {#each [1, 2, 3, 4, 5] as n (n)}
    <span class={'star' + (n <= score ? ' star-on' : '')}>&#9733;</span>
  {/each}
  <span class="rating-count">{(score || 0).toFixed(1)} ({count})</span>
</span>

// bench/react-medium/src/components/Rating.tsx
interface Props {
  score: number;
  count: number;
}

export default function Rating({ score, count }: Props) {
  return (
    <span className="rating">
      {[1, 2, 3, 4, 5].map((n) => (
        <span key={n} className={'star' + (n <= score ? ' star-on' : '')}>&#9733;</span>
      ))}
      <span className="rating-count">{(score || 0).toFixed(1)} ({count})</span>
    </span>
  );
}
