// packages/cli/bench/svelte-medium/src/components/Section.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  let { kicker, heading, actions, children }: {
    kicker: string;
    heading: string;
    actions?: Snippet;
    children: Snippet;
  } = $props();
</script>

<section class="panel">
  <header class="panel-head">
    <div><p class="kicker">{kicker}</p><h2>{heading}</h2></div>
    <div class="panel-actions">{#if actions}{@render actions()}{/if}</div>
  </header>
  {@render children()}
</section>

// bench/react-medium/src/components/Section.tsx
import type { ReactNode } from 'react';

interface Props {
  kicker: string;
  heading: string;
  actions?: ReactNode;
  children: ReactNode;
}

export default function Section({ kicker, heading, actions, children }: Props) {
  return (
    <section className="panel">
      <header className="panel-head">
        <div>
          <p className="kicker">{kicker}</p>
          <h2>{heading}</h2>
        </div>
        <div className="panel-actions">{actions}</div>
      </header>
      {children}
    </section>
  );
}
