// packages/cli/bench/vue-catalog/src/components/Section.vue
<script setup vapor lang="ts">
defineProps<{ kicker: string; heading: string }>();
</script>

<template>
  <section class="panel">
    <header class="panel-head">
      <div><p class="kicker">{{ kicker }}</p><h2>{{ heading }}</h2></div>
      <div class="panel-actions"><slot name="actions" /></div>
    </header>
    <slot />
  </section>
</template>

// bench/react-medium/src/components/Section.tsx
import type { ReactNode } from 'react';

interface Props {
  kicker: string;
  heading: string;
  actions?: ReactNode;
  children: ReactNode;
}

export default function Section({ kicker, heading, actions, children }: Props) {
  return (
    <section className="panel">
      <header className="panel-head">
        <div>
          <p className="kicker">{kicker}</p>
          <h2>{heading}</h2>
        </div>
        <div className="panel-actions">{actions}</div>
      </header>
      {children}
    </section>
  );
}
