// packages/cli/bench/vue-catalog/src/components/Stat.vue
<script setup vapor lang="ts">
defineProps<{ label: string; value: string | number; hint: string }>();
</script>

<template>
  <div class="stat">
    <span class="stat-label">{{ label }}</span>
    <strong class="stat-value">{{ value }}</strong>
    <span class="stat-hint">{{ hint }}</span>
  </div>
</template>

// bench/react-medium/src/components/Stat.tsx
interface Props {
  label: string;
  value: string | number;
  hint: string;
}

export default function Stat({ label, value, hint }: Props) {
  return (
    <div className="stat">
      <span className="stat-label">{label}</span>
      <strong className="stat-value">{value}</strong>
      <span className="stat-hint">{hint}</span>
    </div>
  );
}
